### ISSUE TITLE
Error in I2C communication results in unrecovered HAL deinitialisation.

### ISSUE THREAD

**Issue by krvanek** [SmartCAMPUSZCU/KETCube-fw#2]
**Describe the bug**
Error in I2C communication results in unrecovered HAL deinitialisation.

**To Reproduce**
1. Enabled HDC1080 module
2. HDC1080 sensor not connected

**Expected behavior**
KETCube I2C driver should handle error and leave the bus functional for other modules.

**Additional context**
Function void `ketCube_I2C_Error` called by `ketCube_I2C_WriteData` or `ketCube_I2C_ReadData` de-initialises the HAL driver and calls `ketCube_I2C_Init` which increments the number of initialisation requests but doesn't reinitialise the HAL driver.

**Suggestion:**
`ketCube_I2C_Init` should always check for HAL driver status and initialise the driver when needed.

**Comment by belohoub** [comment]
Hot-fixed by "c1e7085b7015191f1374627bdcb1de309a3c90b7" commit.
