### ISSUE TITLE
Battery status 

### ISSUE THREAD

**Issue by zarubaj** [SmartCAMPUSZCU/KETCube-fw#21]
Add [battery status](https://www.loraserver.io/loraserver/features/device-status/) specified by the LoRaWAN protocol

**device-status battery**
0 - The end-device is connected to an external power source
1..254 - The battery level, 1 being at minimum and 254 being at maximum
255 - The end-device was not able to measure the battery level

**Comment by belohoub** [comment]
Module batMeas should be closely coupled with LoRaWAN stack, which allows reading battery status using MAC command.
